### ISSUE TITLE
Feature request: flag to specify .docheader location

### ISSUE THREAD

**Issue by Xerkus** [malukenho/docheader#15]
Zend Framework uses single package, installed as dev dependency, for its coding style rules.

Ability to specify custom `.docheader` file location will allow it to force uniform header format across all packages:

```sh
 $ docheader check src test --docheader ./vendor/zendframework/zend-coding-standard/.docheader
```

**Comment by weierophinney** [comment]
@Xerkus That said, we should be updating each of the packages to link to their _own_ package for the license and source repository, not a general location. The old docblocks all pointed to the main ZF repository as that's where the code _originated_; since splitting to separate repositories, however, they should point to their own. And if they point to their own, they need their own `.docheader` file as well.

I still think the feature is relevant, just not necessarily for ZF. :)

**Comment by malukenho** [comment]
Handled on #19
