### ISSUE TITLE
Docheader broke Travis tests

### ISSUE THREAD

**Issue by antoine-pous** [malukenho/docheader#17]
I have updated all test for another project and docheader broke the last one.

```sh
$ vendor/bin/docheader check src/ tests/
PHP Fatal error:  Class 'Symfony\Component\Console\Application' not found in /home/travis/build/antoine-pous/PHP-Router/vendor/malukenho/docheader/bin/docheader on line 42
PHP Stack trace:
PHP   1. {main}() /home/travis/build/antoine-pous/PHP-Router/vendor/malukenho/docheader/bin/docheader:0
Fatal error: Class 'Symfony\Component\Console\Application' not found in /home/travis/build/antoine-pous/PHP-Router/vendor/malukenho/docheader/bin/docheader on line 42
```

Travis's full report: https://travis-ci.org/antoine-pous/PHP-Router

**Comment by malukenho** [comment]
Closing as invalid.

@antoine-pous As far as I can see your tests is failing due multiples issues.

First, docheader doesn't work with php versions bellow 5.5. So that explains failures for version 5.3 and 5.4.

Other versions are failing as unit tests is broken, that indicates that bugs were introduced.
If you're having trouble with docheader on your machine. Check if dependencies are installed.

**Comment by antoine-pous** [comment]
mhhh this is not the good entry of Travis tests, here is the last test for the branch `upgrade-phpunit` https://travis-ci.org/antoine-pous/PHP-Router/builds/214020309

All the tests for my PR are passed except the last one where i had the fatal error.
